[package]
name = "playit-agent-core"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
# Internal deps
playit-agent-proto = { path = "../agent_proto" }
# External deps
byteorder = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true, features = ["client", "http2", "http1"] }
hyper-rustls = { workspace = true, features = ["http2"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["serde"] }

[[example]]
name = "echo_tunnel"
path = "examples/echo_tunnel.rs"
