[package]
name = "playit-cli"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
# Internal deps
playit-agent-core = { path = "../agent_core" }
playit-agent-proto = { path = "../agent_proto" }
# External deps
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hex = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
urlencoding = { workspace = true }
uuid = { workspace = true }
