[package]
name = "playit-agent-api"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
# Internal deps
playit-agent-proto = { path = "../agent_proto" }
# External deps
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, default-features = false, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, default-features = false, features = ["serde"] }
