[package]
name = "playit-agent-api"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, default-features = false, features = ["derive"] }
