[package]
name = "playit-agent-proto"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[features]
tokio = ["dep:async-trait", "dep:tokio"]
std = ["dep:byteorder"]

[dependencies]
async-trait = { workspace = true, optional = true }
byteorder = { workspace = true, optional = true }
hmac = { workspace = true }
serde = { workspace = true, default-features = false, features = ["derive"] }
sha2 = { workspace = true }
tokio = { workspace = true, default-features = false, features = ["io-util"], optional = true }

[dev-dependencies]
rand = { workspace = true }
tokio-test = { workspace = true }
