[package]
name = "playit-agent-proto"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
bytes = { workspace = true }
hmac = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
